### ISSUE TITLE
File Existence Tests shouldExist = false raising 'panic: runtime error: invalid memory address or nil pointer dereference' error

### ISSUE THREAD

**Issue by rcabral-splunk** [GoogleContainerTools/container-structure-test#195]
I'm currently running v1.7.0 in OSX with a simple scenario like:

```YAML
fileExistenceTests:
  - name: 'Test missing server.key'
    path: '/usr/local/apache2/conf/server.key'
    shouldExist: false
    permissions: '-rw-r--r--'
```
Then I run `container-structure-test test --image [my-image] --config [myconfig].yml` and I immediately get:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1455569]
goroutine 50 [running]:
github.com/GoogleContainerTools/container-structure-test/pkg/types/v2.FileExistenceTest.Run(0xc000775480, 0x19, 0xc000084150, 0x22, 0x0, 0xc00044c250, 0xa, 0xffffffffffffffff, 0xffffffffffffffff, 0x0, ...)
        /Users/nkubala/Development/go/src/github.com/GoogleContainerTools/container-structure-test/pkg/types/v2/file_existence.go:109 +0xdb9
github.com/GoogleContainerTools/container-structure-test/pkg/types/v2.(*StructureTest).RunFileExistenceTests(0xc0000ae140, 0xc0004582a0)
        /Users/nkubala/Development/go/src/github.com/GoogleContainerTools/container-structure-test/pkg/types/v2/structure.go:117 +0x430
github.com/GoogleContainerTools/container-structure-test/pkg/types/v2.(*StructureTest).runAll(0xc0000ae140, 0xc0004582a0, 0xc000064000)
        /Users/nkubala/Development/go/src/github.com/GoogleContainerTools/container-structure-test/pkg/types/v2/structure.go:56 +0x69
created by github.com/GoogleContainerTools/container-structure-test/pkg/types/v2.(*StructureTest).RunAll
        /Users/nkubala/Development/go/src/github.com/GoogleContainerTools/container-structure-test/pkg/types/v2/structure.go:49 +0x75
```

I couldn't find any similar issue logged so far yet, so wondering someone else had same error.

**Comment by rcabral-splunk** [comment]
I guess I found a workaround for that by removing the `permissions` attribute from my config file. Yes, it doesn't make sense to check a permission on a missing file testing case, but it would be nice if whether this is added to the documentation or have the code ignoring permission test when shouldExist flag is false.

**Comment by nkubala** [comment]
@rcabral-splunk thanks for the issue. this is definitely a bug, I opened a PR for a fix.
